# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm run build

      - run:
          name: Install Zeit Now (CLI)
          command: npm install now
      - run:
          name: Deploy to Staging
          command: |
            npm run push:online -- --token $now_token

      - run:
          name: Map to Production
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              npm run swap:live -- --token $now_token
            else
              echo "SKIP - Not publishing to production for a PR"
            fi